/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cybertruck.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.interior001.geometry} material={materials.lights} />
      <mesh geometry={nodes.interior001_1.geometry} material={materials.body} />
      <mesh geometry={nodes.interior001_2.geometry} material={materials.glass} />
      <mesh geometry={nodes.interior001_3.geometry} material={materials.glassframes} />
      <mesh geometry={nodes.interior001_4.geometry} material={materials.warninglights} />
      <mesh geometry={nodes.interior001_5.geometry} material={materials.black} />
      <mesh geometry={nodes.interior001_6.geometry} material={materials.shader} />
      <mesh geometry={nodes.steer.geometry} material={materials.gray} />
      <mesh geometry={nodes.tires001.geometry} material={materials.tires} />
      <mesh geometry={nodes.tires001_1.geometry} material={materials.rims} />
    </group>
  )
}

useGLTF.preload('/cybertruck.gltf')
